import { codePage } from "../types/globalAdmin3Types";

export const codeListState: codePage[] = [
  { name: "Javascript", code: "javascript" },
  { name: "Markup", code: "markup" },
  { name: "HTML", code: "html" },
  { name: "XML", code: "xml" },
  { name: "SVG", code: "svg" },
  { name: "MathMl", code: "mathml" },
  { name: "SSML", code: "ssml" },
  { name: "Atom", code: "atom" },
  { name: "RSS", code: "rss" },
  { name: "CSS", code: "css" },
  { name: "ABAP", code: "abap" },
  { name: "ABNF", code: "abnf" },
  { name: "ActionScript ", code: "actionscript" },
  { name: "Ada", code: "ada" },
  { name: "Agda", code: "agda" },
  { name: "AL", code: "al" },
  { name: "ANTLR4", code: "antlr4" },
  { name: "Apache Configuration", code: "apacheconf" },
  { name: "Apex", code: "apex" },
  { name: "APL", code: "apl" },
  { name: "AppleScript  ", code: "applescript" },
  { name: "AQL", code: "aql" },
  { name: "Arduino", code: "arduino" },
  { name: "ARFF", code: "arff" },
  { name: "ARM Assembly", code: "armasm" },
  { name: "Arturo", code: "arturo" },
  { name: "AsciiDoc", code: "asciidoc" },
  { name: "ASP.NET (C#)", code: "aspnet" },
  { name: "6502 Assembly", code: "apasm6502" },
  { name: "Atmel AVR Assembly", code: "asmatmel" },
  { name: "AutoHotkey", code: "autohotkey" },
  { name: "AutoIt", code: "autoit" },
  { name: "AviSynth", code: "avisynth" },
  { name: "Avro IDL", code: "avro-idl" },
  { name: "AWK", code: "awk" },
  { name: "Bash", code: "bash" },
  { name: "BASIC", code: "basic" },
  { name: "Batch", code: "batch" },
  { name: "BBcode", code: "bbcode" },
  { name: "BBj", code: "bbj" },
  { name: "Bicep", code: "bicep" },
  { name: "Birb", code: "birb" },
  { name: "Bison", code: "bison" },
  { name: "BNF", code: "bnf" },
  { name: "BQN", code: "bqn" },
  { name: "Brainfuck", code: "brainfuck" },
  { name: "BrightScript", code: "brightscript" },
  { name: "Bro", code: "bro" },
  { name: "BSL", code: "bsl" },
  { name: "C", code: "c" },
  { name: "C#", code: "csharp" },
  { name: "C++", code: "cpp" },
  { name: "CFScript", code: "cfscript" },
  { name: "ChaiScript", code: "chaiscript" },
  { name: "CIL", code: "cil" },
  { name: "Cilk/C", code: "cilkc" },
  { name: "Cilk/C++", code: "cilkcpp" },
  { name: "Clojure", code: "clojure" },
  { name: "CMake", code: "cmake" },
  { name: "COBOL", code: "cobol" },
  { name: "CoffeeScript", code: "coffeescript" },
  { name: "Concurnas", code: "concurnas" },
  { name: "Content-Security-Policy", code: "csp" },
  { name: "Cooklang", code: "cooklang" },
  { name: "Coq", code: "coq" },
  { name: "Crystal", code: "crystal" },
  { name: "CSS Extras", code: "css-extras" },
  { name: "CSV", code: "csv" },
  { name: "CUE", code: "cue" },
  { name: "Cypher", code: "cypher" },
  { name: "D", code: "dart" },
  { name: "DataWeave", code: "dataweave" },
  { name: "DAX", code: "dax" },
  { name: "Dhall", code: "dhall" },
  { name: "Diff", code: "diff" },
  { name: "Django/Jinja2", code: "django" },
  { name: "DNS zone file", code: "dns-zone-file" },
  { name: "Docker", code: "docker" },
  { name: "DOT", code: "dot" },
  { name: "EBNF", code: "ebnf" },
  { name: "EditorConfig", code: "editorconfig" },
  { name: "Eiffel", code: "eiffel" },
  { name: "EJS", code: "ejs" },
  { name: "Elixir", code: "elixir" },
  { name: "Elm", code: "elm" },
  { name: "Embedded Lua templating", code: "etlua" },
  { name: "ERB", code: "erb" },
  { name: "Erlang", code: "erlang" },
  { name: "Excel", code: "xlsx" },
  { name: "F#", code: "fsharp" },
  { name: "Factor", code: "factor" },
  { name: "False", code: "false" },
  { name: "Firestore security rules", code: "firestore-security-rules" },
  { name: "Flow", code: "flow" },
  { name: "Fortran", code: "fortran" },
  { name: "FreeMarker Template Language", code: "ftl" },
  { name: "GameMaker Language", code: "gamemakerlanguage" },
  { name: "GAP", code: "gap" },
  { name: "G-code", code: "gcode" },
  { name: "GDScript", code: "gdscript" },
  { name: "AGEDCOM", code: "gedcom" },
  { name: "gettext", code: "gettext" },
  { name: "Gherkin", code: "gherkin" },
  { name: "Git", code: "git" },
  { name: "GLSL", code: "glsl" },
  { name: "GN", code: "apl" },
  { name: "GNU Linker Script", code: "linker-script" },
  { name: "Go", code: "go" },
  { name: "Go module", code: "go-module" },
  { name: "Gradle", code: "gradle" },
  { name: "GraphQL", code: "graphql" },
  { name: "Groovy", code: "groovy" },
  { name: "Haml", code: "haml" },
  { name: "Handlebars", code: "handlebars" },
  { name: "Haskell", code: "haskell" },
  { name: "Haxe", code: "haxe" },
  { name: "HCL", code: "hcl" },
  { name: "HLSL", code: "hlsl" },
  { name: "Hoon", code: "hoon" },
  { name: "HTTP", code: "http" },
  { name: "HTTP Public-Key-Pins", code: "hpkp" },
  { name: "HTTP Strict-Transport-Security", code: "hsts" },
  { name: "IchigoJam", code: "ichigojam" },
  { name: "Icon", code: "icon" },
  { name: "ICU Message Format", code: "icu-message-format" },
  { name: "Idris", code: "idris" },
  { name: "ignore", code: "ignore" },
  { name: "gitignore", code: "gitignore" },
  { name: "Inform 7", code: "inform7" },
  { name: "Ini", code: "ini" },
  { name: "Io", code: "io" },
  { name: "J", code: "j" },
  { name: "Java", code: "java" },
  { name: "JavaDoc", code: "javadoc" },
  { name: "JavaDoc-like", code: "javadoclike" },
  { name: "Java stack trace", code: "javastacktrace" },
  { name: "Jexl", code: "jexl" },
  { name: "Jolie", code: "jolie" },
  { name: "JQ", code: "jq" },
  { name: "JSDoc", code: "jsdoc" },
  { name: "JS Extras", code: "js-extras" },
  { name: "JSON", code: "json" },
  { name: "JSON5", code: "json5" },
  { name: "JSONP", code: "jsonp" },
  { name: "JS stack trace", code: "jsstacktrace" },
  { name: "JS Templates", code: "js-templates" },
  { name: "Julia", code: "julia" },
  { name: "Keepalived Configure", code: "keepalived" },
  { name: "Keyman", code: "keyman" },
  { name: "Kotlin", code: "kotlin" },
  { name: "KuMir (КуМир)", code: "kumir" },
  { name: "Kusto", code: "kusto" },
  { name: "LaTeX", code: "latex" },
  { name: "Latte", code: "latte" },
  { name: "Less", code: "less" },
  { name: "LilyPond", code: "lilypond" },
  { name: "Liquid", code: "liquid" },
  { name: "Lisp", code: "lisp" },
  { name: "LiveScript", code: "livescript" },
  { name: "LLVM IR", code: "llvm" },
  { name: "Log file", code: "log" },
  { name: "LOLCODE", code: "lolcode" },
  { name: "Lua", code: "lua" },
  { name: "Magma (CAS)", code: "magma" },
  { name: "Makefile", code: "makefile" },
  { name: "Markdown", code: "markdown" },
  { name: "Markup templating", code: "markup-templating" },
  { name: "Mata", code: "mata" },
  { name: "MATLAB", code: "matlab" },
  { name: "MAXScript", code: "maxscript" },
  { name: "MEL", code: "mel" },
  { name: "Mermaid", code: "mermaid" },
  { name: "METAFONT", code: "metafont" },
  { name: "Mizar", code: "mizar" },
  { name: "MongoDB", code: "mongodb" },
  { name: "Monkey", code: "monkey" },
  { name: "MoonScript", code: "moonscript" },
  { name: "N1QL", code: "n1ql" },
  { name: "N4JS", code: "n4js" },
  { name: "Nand To Tetris HDL", code: "nand2tetris-hdl" },
  { name: "Naninovel Script", code: "naniscript" },
  { name: "NASM", code: "nasm" },
  { name: "NEON", code: "neon" },
  { name: "Nevod", code: "nevod" },
  { name: "nginx", code: "nginx" },
  { name: "Nim", code: "nim" },
  { name: "Nix", code: "nix" },
  { name: "NSIS", code: "nsis" },
  { name: "Objective-C", code: "objectivec" },
  { name: "APL", code: "apl" },
  { name: "OCaml", code: "ocaml" },
  { name: "Odin", code: "odin" },
  { name: "OpenCL", code: "opencl" },
  { name: "OpenQasm", code: "openqasm" },
  { name: "Oz", code: "oz" },
  { name: "PARI/GP", code: "parigp" },
  { name: "Parser", code: "parser" },
  { name: "Pascal", code: "pascal" },
  { name: "ObjectPascal", code: "objectpascal" },
  { name: "Pascaligo", code: "pascaligo" },
  { name: "PATROL Scripting", code: "psl" },
  { name: "PC-Axis", code: "pcaxis" },
  { name: "PeopleCode", code: "peoplecode" },
  { name: "Perl", code: "perl" },
  { name: "PHP", code: "php" },
  { name: "PHPDoc", code: "phpdoc" },
  { name: "PHP Extras", code: "php-extras" },
  { name: "PlantUML", code: "plant-uml" },
  { name: "PL/SQL", code: "plsql" },
  { name: "PowerQuery", code: "powerquery" },
  { name: "PowerShell", code: "powershell" },
  { name: "Processing", code: "processing" },
  { name: "Prolog", code: "prolog" },
  { name: "PromQL", code: "promql" },
  { name: "properties", code: "properties" },
  { name: "Protocol Buffers", code: "protobuf" },
  { name: "Pug", code: "pug" },
  { name: "Puppet", code: "puppet" },
  { name: "Pure", code: "pure" },
  { name: "PureBasic", code: "purebasic" },
  { name: "PureScript", code: "purescript" },
  { name: "Python", code: "python" },
  { name: "Q#", code: "qsharp" },
  { name: "Q", code: "q" },
  { name: "QML", code: "qml" },
  { name: "Qore", code: "qore" },
  { name: "R", code: "r" },
  { name: "Racket", code: "racket" },
  { name: "Razor C#", code: "razor" },
  { name: "React JSX", code: "jsx" },
  { name: "React TSX", code: "tsx" },
  { name: "Reason", code: "reason" },
  { name: "Regex", code: "regex" },
  { name: "Rego", code: "rego" },
  { name: "Ren'py", code: "renpy" },
  { name: "ReScript", code: "rescript" },
  { name: "reST (reStructuredText)", code: "rest" },
  { name: "Rip", code: "rip" },
  { name: "Roboconf", code: "roboconf" },
  { name: "Robot Framework", code: "robotframework" },
  { name: "Ruby", code: "ruby" },
  { name: "Rust", code: "rust" },
  { name: "SAS", code: "sas" },
  { name: "Sass (Sass)", code: "sass" },
  { name: "Sass (SCSS)", code: "scss" },
  { name: "Scala", code: "scala" },
  { name: "Scheme", code: "scheme" },
  { name: "Shell session", code: "shell-session" },
  { name: "Smali", code: "smali" },
  { name: "Smalltalk", code: "smalltalk" },
  { name: "Smarty", code: "smarty" },
  { name: "SML", code: "sml" },
  { name: "Solidity (Ethereum)", code: "solidity" },
  { name: "Solution file", code: "solution-file" },
  { name: "Soy (Closure Template)", code: "soy" },
  { name: "SPARQL", code: "apl" },
  { name: "Splunk SPL", code: "splunk-spl" },
  { name: "SQF", code: "sqf" },
  { name: "SQL", code: "sql" },
  { name: "Squirrel", code: "squirrel" },
  { name: "Stan", code: "stan" },
  { name: "Stata Ado", code: "stata" },
  { name: "Structured Text (IEC 61131-3)", code: "iecst" },
  { name: "Stylus", code: "stylus" },
  { name: "SuperCollider", code: "supercollider" },
  { name: "Swift", code: "swift" },
  { name: "Systemd configuration file", code: "systemd" },
  { name: "T4 templating", code: "t4-templating" },
  { name: "T4 Text Templates (C#)", code: "t4-cs" },
  { name: "T4 Text Templates (VB)", code: "t4-vb" },
  { name: "TAP", code: "tap" },
  { name: "Tcl", code: "tcl" },
  { name: "Template Toolkit 2", code: "tt2" },
  { name: "Textile", code: "textile" },
  { name: "TOML", code: "toml" },
  { name: "Tremor", code: "tremor" },
  { name: "Turtle", code: "turtle" },
  { name: "Twig", code: "twig" },
  { name: "TypeScript", code: "typescript" },
  { name: "TypoScript", code: "typoscript" },
  { name: "UnrealScript", code: "unrealscript" },
  { name: "UO Razor Script", code: "uorazor" },
  { name: "URI", code: "uri" },
  { name: "V", code: "v" },
  { name: "Vala", code: "vala" },
  { name: "VB.Net", code: "vbnet" },
  { name: "Velocity", code: "velocity" },
  { name: "Verilog", code: "verilog" },
  { name: "VHDL", code: "vhdl" },
  { name: "vim", code: "vim" },
  { name: "Visual Basic", code: "visual-basic" },
  { name: "WarpScript", code: "warpscript" },
  { name: "WebAssembly", code: "wasm" },
  { name: "Web IDL", code: "web-idl" },
  { name: "WGSL", code: "wgsl" },
  { name: "Wiki markup", code: "wiki" },
  { name: "Wolfram language", code: "wolfram" },
  { name: "Wren", code: "wren" },
  { name: "Xeora", code: "xeora" },
  { name: "XML doc (.net)", code: "xml-doc" },
  { name: "Xojo (REALbasic)", code: "xojo" },
  { name: "XQuery", code: "xquery" },
  { name: "YAML", code: "yaml" },
  { name: "YANG", code: "yang" },
  { name: "Zig", code: "zig" },
];
